---
- name: Br-netfilter module is loaded
  ansible.builtin.modprobe:
    name: br_netfilter
    state: present

- name: Ensure br-netfilter is loaded on boot
  ansible.builtin.lineinfile:
    dest: /etc/modules-load.d/br_netfilter.conf
    state: present
    line: 'br_netfilter'

- name: Config sysctl for Kubernetes networking
  ansible.builtin.lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^net.bridge.bridge-nf-call-iptables'
    line: 'net.bridge.bridge-nf-call-iptables = 0'
    state: present

- name: Config sysctl for Kubernetes networking
  ansible.builtin.lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^net.bridge.bridge-nf-call-ip6tables'
    line: 'net.bridge.bridge-nf-call-ip6tables = 0'
    state: present

- name: Overlay module is loaded
  ansible.builtin.modprobe:
    name: overlay
    state: present

- name: Ensure overlay is loaded on boot
  ansible.builtin.lineinfile:
    dest: /etc/modules-load.d/overlay.conf
    state: present
    line: 'overlay'

- name: Config sysctl for Kubernetes networking
  ansible.builtin.lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^net.ipv4.conf.all.rp_filter'
    line: 'net.ipv4.conf.all.rp_filter = 1'
    state: present

- name: Config vm.max_map_count
  ansible.builtin.lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^vm.max_map_count'
    line: 'vm.max_map_count = 262144'
    state: present

- name: Config fs.inotify.max_user_watches
  ansible.builtin.lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^fs.inotify.max_user_watches'
    line: 'fs.inotify.max_user_watches = 1048576'
    state: present

- name: Config fs.file-max
  ansible.builtin.lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^fs.file-max'
    line: 'fs.file-max = 2097152'
    state: present

- name: Config fs.inotify.max_user_instances
  ansible.builtin.lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^fs.inotify.max_user_instances'
    line: 'fs.inotify.max_user_instances = 8192'
    state: present

- name: Config /etc/sysctl.conf for kernel parameters
  ansible.builtin.lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^net.ipv4.ip_forward'
    line: 'net.ipv4.ip_forward = 1'
    state: present

- name: Systemd-sysctl (auto reload)
  ansible.builtin.service:
    name: systemd-sysctl
    state: restarted
